// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/go-mumu/cs-go/config"
	"github.com/go-mumu/cs-go/dal"
	"github.com/go-mumu/cs-go/dal/dao"
	"github.com/go-mumu/cs-go/handler"
	"github.com/go-mumu/cs-go/mysql"
	"github.com/go-mumu/cs-go/server"
)

// Injectors from injector.go:

// InitApp 注入全局应用程序
func InitApp() (*App, func(), error) {
	configConfig := config.Init()
	defMysql := mysql.InitDef(configConfig)
	wxuserDao := dao.NewWxuserDao(defMysql)
	dalDao := dal.NewDao(wxuserDao)
	serverServer := server.NewServer()
	userServiceHandler := handler.NewUserServiceHandler(dalDao)
	handlers := handler.NewHandlers(userServiceHandler)
	app := &App{
		DefMysql: defMysql,
		Config:   configConfig,
		Dao:      dalDao,
		Server:   serverServer,
		Handlers: handlers,
	}
	return app, func() {
	}, nil
}
