mysql_def:
  username: web_user
  password: l%meFN!Z88yRgrjz
  protocol: tcp
  address: rm-2zeti0v9e6940n93p.mysql.rds.aliyuncs.com
  port: 3306
  dbname: dushuhui
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: 172.17.223.142:6379
  password:
  database: 0
  prefix_key: csapi_
  read_timeout_ms: 200
  write_timeout_ms: 300

rpc_config:
  grpc_addr: :8992
  http_addr: :8991

  grpc_handler_timeout: 1200000

  http_read_timeout: 120000
  http_write_timeout: 120000

  max_body_size: 167772160

  http_idle_timeout_ms: 120000
  grpc_idle_timeout_ms: 120000

rpc:
  # 20M(byte)
  max_msg_size_byte: 20971520
  # keep-alive 最大空闲时长
  max_connection_idle_ms: 120000
  # context.WithTimeout 默认超时时间
  default_context_timeout_ms: 1200000

  http_read_timeout_ms: 120000
  http_write_timeout_ms: 120000

  http_idle_timeout_ms: 120000
  grpc_idle_timeout_ms: 120000

service:
  service_name: cs-go-service
  node1:
    id: cs-go-service1
    name: cs-go-service
    addr: 127.0.0.1
    port: 8992
    timeout: 5s
    interval: 5s

client:
  service_addr: 127.0.0.1

domain:
  center: https://test-internal-open.weimiaocaishang.com

interest:
  code: QY20220428001
  msg: name