// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/go-mumu/cs-go/library/mysql"
	"github.com/go-mumu/cs-go/service/container/provider"
	"github.com/go-mumu/cs-go/service/dal/dao"
	"github.com/go-mumu/cs-go/service/handler"
)

// Injectors from injector.go:

// InitApp 注入全局应用程序
func InitApp() (*App, func(), error) {
	defMysql := mysql.InitDef()
	wxuserDao := dao.NewWxuserDao(defMysql)
	userServiceHandler := handler.NewUserServiceHandler(wxuserDao)
	providerHandler := provider.NewHandler(userServiceHandler)
	server := provider.NewServer(providerHandler)
	app := &App{
		DefMysql: defMysql,
		Server:   server,
		Handler:  providerHandler,
	}
	return app, func() {
	}, nil
}

// injector.go:

// App 全局应用程序
type App struct {
	DefMysql *mysql.DefMysql
	Server   *provider.Server
	Handler  *provider.Handler
}
