// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/go-mumu/cs-go/config"
	"github.com/go-mumu/cs-go/mysql"
)

// Injectors from injector.go:

// InitApp 注入全局应用程序
func InitApp() (*App, func(), error) {
	configConfig := config.Init()
	defMysql := mysql.InitDef(configConfig)
	app := &App{
		DefMysql: defMysql,
		Config:   configConfig,
	}
	return app, func() {
	}, nil
}
