// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: user_struct.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsVipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *IsVipReq) Reset() {
	*x = IsVipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsVipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVipReq) ProtoMessage() {}

func (x *IsVipReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVipReq.ProtoReflect.Descriptor instead.
func (*IsVipReq) Descriptor() ([]byte, []int) {
	return file_user_struct_proto_rawDescGZIP(), []int{0}
}

func (x *IsVipReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type IsVipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vip7        int32  `protobuf:"varint,1,opt,name=vip7,proto3" json:"vip7,omitempty"`
	Overdue     int32  `protobuf:"varint,2,opt,name=overdue,proto3" json:"overdue,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Viptime     string `protobuf:"bytes,4,opt,name=viptime,proto3" json:"viptime,omitempty"`
	Vipvalidity string `protobuf:"bytes,5,opt,name=vipvalidity,proto3" json:"vipvalidity,omitempty"`
}

func (x *IsVipRes) Reset() {
	*x = IsVipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsVipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVipRes) ProtoMessage() {}

func (x *IsVipRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVipRes.ProtoReflect.Descriptor instead.
func (*IsVipRes) Descriptor() ([]byte, []int) {
	return file_user_struct_proto_rawDescGZIP(), []int{1}
}

func (x *IsVipRes) GetVip7() int32 {
	if x != nil {
		return x.Vip7
	}
	return 0
}

func (x *IsVipRes) GetOverdue() int32 {
	if x != nil {
		return x.Overdue
	}
	return 0
}

func (x *IsVipRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IsVipRes) GetViptime() string {
	if x != nil {
		return x.Viptime
	}
	return ""
}

func (x *IsVipRes) GetVipvalidity() string {
	if x != nil {
		return x.Vipvalidity
	}
	return ""
}

var File_user_struct_proto protoreflect.FileDescriptor

var file_user_struct_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x08, 0x49, 0x73, 0x56, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69,
	0x64, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x49, 0x73, 0x56, 0x69, 0x70, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x69, 0x70, 0x37, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x69,
	0x70, 0x37, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x76, 0x65, 0x72, 0x64, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x76, 0x65, 0x72, 0x64, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x69, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69,
	0x70, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x76, 0x69, 0x70, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_struct_proto_rawDescOnce sync.Once
	file_user_struct_proto_rawDescData = file_user_struct_proto_rawDesc
)

func file_user_struct_proto_rawDescGZIP() []byte {
	file_user_struct_proto_rawDescOnce.Do(func() {
		file_user_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_struct_proto_rawDescData)
	})
	return file_user_struct_proto_rawDescData
}

var file_user_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_struct_proto_goTypes = []interface{}{
	(*IsVipReq)(nil), // 0: IsVipReq
	(*IsVipRes)(nil), // 1: IsVipRes
}
var file_user_struct_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_struct_proto_init() }
func file_user_struct_proto_init() {
	if File_user_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsVipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsVipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_struct_proto_goTypes,
		DependencyIndexes: file_user_struct_proto_depIdxs,
		MessageInfos:      file_user_struct_proto_msgTypes,
	}.Build()
	File_user_struct_proto = out.File
	file_user_struct_proto_rawDesc = nil
	file_user_struct_proto_goTypes = nil
	file_user_struct_proto_depIdxs = nil
}
